image:
  repository: tccr.io/truecharts/heimdall
  tag: v2.4.13@sha256:9c766bbe9f2880c67f41fcc3527c328a5c114973bd09362fda1d4dc9e1720397
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

probes:
  startup:
    enabled: true

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
